### ISSUE TITLE
Add openSUSE's implementation of toolbox in the list

### ISSUE THREAD

**Issue by thecoder-001** [castrojo/awesome-immutable#20]
Hello!
Found your awesome list from your [blog-post](https://www.ypsidanger.com/comparing-opensuse-microos-to-fedora-silverblue-37/) comparing microOS and silverblue.
While going through the list I found that you have omitted openSUSE's implementation of toolbox: [openSUSE/microos-toolbox](https://github.com/openSUSE/microos-toolbox). 
Maybe it would be a good idea to add it to the list? Or has openSUSE dropped its supported considering that microos now ships Distrobox by default (though it still seems to be available in tumbleweed under the package name `toolbox`)?

**Comment by castrojo** [comment]
Yeah it has distrobox by default now and it has so many better features and community that people are just better off starting with that.
