### ISSUE TITLE
Include APX under the Toolboxes section.

### ISSUE THREAD

**Issue by abuhuraira0099** [castrojo/awesome-immutable#28]
VanillaOS has a great tool named APX, which lets you install, update and manage packages using distrobox easily with simple commands from different Linux distribution repositories (including AUR). It also lets you install nix packages without having to right any config file. It automatically creates a .desktop file to let the GUI apps to show up in your host's app menu. I think this tool deserves to be mentioned in this thread.

**Comment by abuhuraira0099** [comment]
Link to the APX repository : 
https://github.com/Vanilla-OS/apx

**Comment by Dvlv** [comment]
Thanks for the suggestion, added!
