### ISSUE TITLE
Mention ABRoot in the lower level tools' list

### ISSUE THREAD

**Issue by abuhuraira0099** [castrojo/awesome-immutable#29]
"abroot is a utility that provides complete immutability and atomicity by making transactions between 2 root partitions (A⟺B), it also allows for on-demand transactions via a transactional shell."
- Quote from the official documentation page. More on ABRoot : https://documentation.vanillaos.org/docs/ABRoot/

**Comment by Dvlv** [comment]
Thanks for the suggestion, added!
