### ISSUE TITLE
[Request] Elemental Toolkit

### ISSUE THREAD

**Issue by GrabbenD** [castrojo/awesome-immutable#37]
I was researching tools for building a bootable system through (immutable) OCI image based image with A/B deployment (anything similar to KairOS) and stumbled upon this project and wanted to share it here:
- About: https://rancher.github.io/elemental-toolkit/docs/
- More: https://rancher.github.io/elemental-toolkit/docs/getting-started/
- Homepage: https://rancher.github.io/elemental-toolkit/

**Comment by Dvlv** [comment]
Thanks, added to Lower Level tools!
