### ISSUE TITLE
[Request] Honorable mention of BootC?

### ISSUE THREAD

**Issue by GrabbenD** [castrojo/awesome-immutable#38]
[RPM-OSTree](https://coreos.github.io/rpm-ostree/container/) + [LibOSTree](https://ostree.readthedocs.io/en/stable/#operating-systems-and-distributions-using-ostree) makes it possible to deliver bootable images through Docker/OCI transport. Using these tools within the RPM-ecosystem allows projects to create a immutable OSes like Fedora MicroOS. From my understanding it's restricted to RPM based systems for now due to [three way merge of /etc requirement](https://blog.verbum.org/2014/01/24/why-ostree-requires-usretc/) (check [Lennart Pottering’s “hermetic /usr" concept for more info](https://0pointer.net/blog/fitting-everything-together.html))

While researching the above I came across `BootC` which continues the work of RPM-OSTree:
> Create bootable transactional, in-place operating system updates using OCI/Docker container images.
> https://github.com/containers/bootc

Wanted to share it here to spread awarness!

**Comment by Dvlv** [comment]
Thanks, added to Lower Level tools!
