### ISSUE TITLE
Yet another Build-Your-Own-Silverblue

### ISSUE THREAD

**Issue by electricduck** [castrojo/awesome-immutable#4]
Was unsure whether or not [my extensive Silverblue config I built that I use on a daily basis](https://github.com/electricduck/sodalite) belongs here:
 * It doesn't use Ansible (something I've literally never used myself) so there wasn't an appropriate header to stick it under.
 * Wasn't sure whether you wanted yet another Silverblue distro sitting in the list.

In a nutshell, similar to [Ublue](https://github.com/castrojo/ublue), I decided to take up building the OS I'd been used to for many years (elementaryOS) onto Fedora Silverblue. And now its my daily driver; seemed a shame not to let others see it.

 Do with it what you will though :smile:

**Comment by castrojo** [comment]
Wow, I am in shock, this is _exactly_ what I hoped someone would build. I hope in the future that all derivative distributions are built this way so they can concentrate on the end-user UX instead of maintaining their own separate OS.
