### ISSUE TITLE
[Request] GoldBoot

### ISSUE THREAD

**Issue by GrabbenD** [castrojo/awesome-immutable#40]
Came across this project for bootstrapping immutable images, [GoldBoot](https://github.com/fossable/goldboot):
> goldboot is a command-line utility similar in nature to [Packer](https://github.com/hashicorp/packer) that builds machine images for both servers and workstations alike.

Unlike similar projects like RPM-OSTree, Elemental-Toolkit and KairOS which builds images from scratch, this project aids in automating the bootstrapping/provisioning of existing/official images as seen in the example here https://github.com/fossable/goldboot/blob/master/examples/ArchLinux/goldboot.json

**Comment by Dvlv** [comment]
Thanks, added to Lower Level Tools!
