### ISSUE TITLE
Add Arkane Linux

### ISSUE THREAD

**Issue by user1-github** [castrojo/awesome-immutable#49]
I recently found out about [Arkane Linux](https://arkanelinux.org), a new interesting Arch based immutable distro, which utilizes [Arkdep](https://github.com/arkanelinux/arkdep) - its in house toolkit for building, deploying and maintaining immutable, atomic, btrfs-based systems.
I think info about Arkdep can be added to the "Lower level tools" section.

**Comment by Malix-off** [comment]
@user1-github good proposal !
Do you want to make the pull request for it ?

**Comment by user1-github** [comment]
> @user1-github good proposal ! Do you want to make the pull request for it ?

Hi,

I prefer someone who already contributed to the repo will do it.

Under "Distributions" section you can simply add:

[Arkane Linux](https://arkanelinux.org/) - Arch based immutable distro, which utilizes [Arkdep](https://github.com/arkanelinux/arkdep)

Under "Lower level tools section you can simply add:

[Arkdep](https://github.com/arkanelinux/arkdep) - Toolkit for building, deploying and maintaining immutable, atomic, btrfs-based systems

**Comment by user1-github** [comment]
Awesome, thanks!
